theme: jekyll-theme-slate
# standard jekyll configuration

permalink: /posts/:title/
exclude: ['Rakefile', 'README.md', 'config.rb', "Gemfile", "Gemfile.lock", "vendor"]
markdown: kramdown

domain: blindtex.org
title: BlindTex
description: Herramientas de accesibilidad de LaTex, especializada para personas invidentes.
avatar: /img/avatar.png
author: BlindTex Team
email:
github_project: https://github.com/blindtex/blindtex
api_app: https://blindtex-app.herokuapp.com

# configuration for ehancements, uncomment to enable

google_analytics:
  account: UA-115000681-1

plugins:
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: atom.xml

sass:
  style: :compressed
